
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd src/
        nuget sources add -name nugetizer3000 -Source https://ci.appveyor.com/nuget/nugetizer3000
        nuget restore
        cd Adobe.ACPUserProfile.Android/
        msbuild -t:build
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd src/
        nuget sources add -name nugetizer3000 -Source https://ci.appveyor.com/nuget/nugetizer3000
        nuget restore
        cd Adobe.ACPUserProfile.iOS/
        msbuild -t:build
        msbuild -t:pack
